version: 2.1

orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-s3: circleci/aws-s3@2.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@2.0.2

jobs:
  frontend:
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/udagram-frontend
    steps:
      - node/install:
          node-version: "14.15"
      - checkout:
          path: ~/udagram-frontend
      - aws-cli/install
      - aws-cli/setup
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: check node version
          command: node --version
      - run:
          name: Front-End Install
          command: npm run frontend:install
      - run:
          name: Front-End Build
          command: npm run frontend:build
      - run:
          name: Front-End Test
          command: echo "skip npm run frontend:test"
      - run:
          name: Deploy Front-End
          command: npm run frontend:deploy
  backend:
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/udagram-api
    steps:
      - node/install
      - checkout:
          path: ~/udagram-api
      - aws-cli/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Back-End Build
          command: npm run backend:build
      - run:
          name: Back-End Test
          command: echo "npm run backend:test -- but no tests"
      - run:
          name: Deploy Back-End
          command: npm run backend:deploy

workflows:
  sample:
    jobs:
      - frontend:
          filters:
            branches:
              only: main
      - backend:
          filters:
            branches:
              only: main
